#!/bin/bash

################################################################################
# Copyright 2011 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may not
# use this file except in compliance with the License. A copy of the License is
# located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions
# and limitations under the License.
################################################################################

if [ "$EUID" -ne 0 ]; then
    echo "You are not root"
    exit 1
fi

# Continue if there is a failure
set +e

if [ -d /etc/update-motd.d ]; then
    rm -f /var/run/motd.tmp
    if [ -f /etc/motd.head ]; then
        cat /etc/motd.head >> /var/run/motd.tmp
    fi
    # Simulated run-parts, wildcards in bash are expanded sorted
    # Skip files ending in ~ or ,
    for part in /etc/update-motd.d/*[^~,]; do
        # Skip .rpmnew, etc.
        [[ $part =~ \.rpm* ]] && continue
        # Run only if it's a regular file and executable
        [ -f $part ] && [ -x $part ] && $part >> /var/run/motd.tmp
    done
    if [ -f /etc/motd.tail ]; then
        cat /etc/motd.tail >> /var/run/motd.tmp
    fi
    mv /var/run/motd.tmp /var/run/motd
fi
